# Generated by Django 5.1.2 on 2024-11-05 14:12

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('surname', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='surname')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoria')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Wydawca')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name')),
            ],
            options={
                'verbose_name': 'Wydawca',
                'verbose_name_plural': 'Wydawcy',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('ASIN', models.CharField(max_length=11, verbose_name='ASIN')),
                ('publication_date', models.DateField(verbose_name='Data publikacji')),
                ('description', models.TextField(verbose_name='Opis')),
                ('page_count', models.IntegerField(verbose_name='Liczba stron')),
                ('image', models.ImageField(default='default.jpg', upload_to='book_pics')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Kategoria')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.publisher', verbose_name='Wydawca')),
            ],
            options={
                'verbose_name': 'Książka',
                'verbose_name_plural': 'Książki',
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(blank=True, help_text='6 cyfrowy kod książki', max_length=6, null=True, unique=True, verbose_name='Kod książki')),
                ('status', models.CharField(choices=[('available', 'Dostępna'), ('borrowed', 'Wypożyczona'), ('reserved', 'Zarezerwowana'), ('maintenance', 'W konserwacji')], default='available', max_length=20, verbose_name='Status książki')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'verbose_name': 'Egzemplarz książki',
                'verbose_name_plural': 'Egzemplarze książek',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=256, verbose_name='Treść komentarza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytana')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Książka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='Data wypożyczenia')),
                ('due_date', models.DateField(verbose_name='Termin zwrotu')),
                ('returned', models.BooleanField(default=False, verbose_name='Zwrócono')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Data zwrotu')),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookinstance', verbose_name='Egzemplarz książki')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wypożyczenie',
                'verbose_name_plural': 'Wypożyczenia',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('borrow', 'Wypożyczenie'), ('return', 'Zwrot')], max_length=10, verbose_name='Typ operacji')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data operacji')),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookinstance', verbose_name='Egzemplarz książki')),
                ('loan', models.ForeignKey(blank=True, help_text='ID wypożyczenia dla operacji wypożyczenia lub zwrotu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.loan', verbose_name='Powiązane wypożyczenie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Operacja',
                'verbose_name_plural': 'Operacje',
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Książka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Ulubiona książka',
                'verbose_name_plural': 'Ulubione książki',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
